quarkiverse/quarkus-mcp-server

deployment/src/test/java/io/quarkiverse/mcp/server/test/close/CloseTest.java
runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessagesHandler.java
runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpServerRecorder.java

- also add non-standard "q/close" operation that can be used by the client explicitly

Make sure MCP connection is closed when HTTP connection is closed

---

.github/workflows/release-prepare.yml

This adds a `workflow_dispatch` event which can be triggered in https://github.com/quarkiverse/quarkus-mcp-server/actions/workflows/release-prepare.yml

Allow retrying a failed release

---

transports/sse/pom.xml
transports/sse/runtime/src/main/resources/META-INF/quarkus-extension.yaml
transports/stdio/pom.xml
transports/stdio/runtime/src/main/resources/META-INF/quarkus-extension.yaml

follow up to #26 which missed that the new sse and stdio extensions doesn't have any metadata so the descriptions are generic/wrong.
This fixes it - but does require new release.

fix: add metadata so sse/stdio shows up with description in code.quarkus and maven central

---

transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpMessageHandler.java

this do graceful exit when EOF because when you quit Claude Desktop java processes keeps hanging around as no signal is otherwise sent.
Also stdio spec at https://spec.modelcontextprotocol.io/specification/2024-11-05/basic/transports/ states "Close stdin, terminate subprocess"
Thus I think this is actual a bug/missing feature.

feat: honor EOF as graceful exit

---

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java
core/deployment/src/test/java/io/quarkiverse/mcp/server/deployment/McpServerProcessorTest.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/ContentEncoder.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/Encoder.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/Prompt.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/PromptResponseEncoder.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/Resource.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceContentsEncoder.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceTemplate.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/Tool.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/ToolResponseEncoder.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/EncoderMapper.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/EncoderResultMapper.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureManager.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/JsonTextContentEncoder.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/JsonTextResourceContentsEncoder.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ListEncoderResultMapper.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpException.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptEncoderResultMapper.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceContentsEncoderResultMapper.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceManager.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResultMappers.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolEncoderResultMapper.java
docs/modules/ROOT/pages/index.adoc
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/prompts/PromptCustomResponseEncoderTest.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/ResourceJsonTextContentEncoderTest.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/ToolCustomContentEncoderTest.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/ToolCustomResponseEncoderTest.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/ToolJsonTextContentEncoderTest.java

- resolves #85
We introduce several encoders that can be used to encode any return value to a relevant response type. 
Specifically, there is `ToolResponseEncoder` that could be used to encode any return value to a `ToolResponse`; `ContentEncoder` to encode any return value to `Content`; `ResourceContentsEncoder` to `ResourceContents` and `PromptResponseEncoder` to `PromptResponse`. 
We also register `JsonTextContentEncoder` and `JsonTextResourceContentsEncoder` by default. As a result, any "custom" return value returned from a `@Tool` method is encoded as `TextContent` containing the value encoded as JSON (using Jackson), and any "custom" return value returned from a `@Resource` method is encoded as `TextResourceContents` containing the value encoded as JSON (using Jackson).

core: introduce API to encode return values as response objects

---

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/CompletePrompt.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/CompleteResourceTemplate.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/McpLog.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/Prompt.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/PromptResponseEncoder.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/Resource.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceTemplate.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/Tool.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessageHandler.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResultMappers.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/TrafficLogger.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/config/McpRuntimeConfig.java
docs/modules/ROOT/pages/includes/quarkus-mcp-server-core.adoc
docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.adoc
docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.mcp.adoc
docs/modules/ROOT/pages/index.adoc
transports/stdio/integration-tests/src/test/java/io/quarkiverse/mcp/server/stdio/it/ServerFeaturesIT.java
transports/stdio/pom.xml

* Rename propmpResultMapper method to promptResultMapper
* Typos fixes
* Fix TrafficLogger to apply textPayloadLimit
* Use System.out.printf instead of String.format and System.out.println combo
* Fix links to the specification
* Update JavaDoc params
* Used method reference instead of lambda

Code adjustment - typos, method names, links

---

docs/modules/ROOT/pages/includes/quarkus-mcp-server-stdio.adoc
docs/modules/ROOT/pages/includes/quarkus-mcp-server-stdio_quarkus.mcp.adoc
docs/modules/ROOT/pages/index.adoc
transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpServerRecorder.java
transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/config/McpStdioRuntimeConfig.java

It's a draft for now - the missing part is disabling the `StdioConfigBuilderCustomizer` that sets `quarkus.log.console.stderr=true`.
CC @maxandersen

stdio: make it possible to disable the transport completely

---

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/WrapBusinessError.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolMessageHandler.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/WrapBusinessErrorInterceptor.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/config/McpRuntimeConfig.java
docs/modules/ROOT/pages/includes/quarkus-mcp-server-core.adoc
docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.mcp.adoc
docs/modules/ROOT/pages/index.adoc
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/ToolBusinessErrorTest.java

Introduce WrapBusinessError interceptor binding

---

README.md
docs/modules/ROOT/pages/includes/quarkus-mcp-server-sse.adoc
docs/modules/ROOT/pages/includes/quarkus-mcp-server-sse_quarkus.mcp.adoc
docs/modules/ROOT/pages/index.adoc
transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/config/McpSseBuildTimeConfig.java

Fix docs - escape the "{rootPath}"

---

core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessageHandler.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/TrafficLogger.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/config/McpRuntimeConfig.java
docs/modules/ROOT/pages/includes/quarkus-mcp-server-core.adoc
docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.mcp.adoc
docs/modules/ROOT/pages/includes/quarkus-mcp-server-sse_quarkus.adoc
transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpConnection.java
transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpMessageHandler.java
transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpServerRecorder.java
transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpConnection.java
transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpMessageHandler.java

- if an MCP client attempts to reconnect an SSE connection but does not reinitialize propertly, we could perform a "dummy" initialization
This PR does not fix #102 because when the app is restarted, the HTTP SSE connection is closed and there's not much we can do about it. However, some MCP clients (such as [MCP Inspector](https://modelcontextprotocol.io/docs/tools/inspector)) do attempt to reconnect but do not reinitialize MCP properly. With this change, we perform a "dummy" initialization when needed and so the subsequent requests can be processed as normally.
CC @maxandersen @sebastienblanc

sse: introduce dummy init in the dev mode

---

devtools/stdio-sse-proxy/README.md
devtools/stdio-sse-proxy/src/main/java/io/quarkiverse/mcp/server/proxy/StdioSseProxy.java
devtools/stdio-sse-proxy/src/main/resources/application.properties

- make the released proxy jar directly runnable
- remove unneeded --quiet
- document runnable jar coordinates (works when this is released)

fix: make proxy a runnable jar from maven

---

transports/sse/integration-tests/pom.xml
transports/stdio/integration-tests/pom.xml

Without this, the tests might either use an outdated artifact or, when building the project tree for the first time, fail the build with
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.19.2:build (default) on project quarkus-mcp-server-stdio-integration-tests: Failed to build quarkus application: The following errors were encountered while processing Quarkus application dependencies:
[ERROR] 1) io.quarkus.bootstrap.resolver.maven.BootstrapMavenException: Failed to resolve artifact io.quarkiverse.mcp:quarkus-mcp-server-core-deployment:jar:999-SNAPSHOT
[ERROR]   at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyResolver$AppDep.initResolvedDependency(ApplicationDependencyResolver.java:531)
[ERROR]   ...
[ERROR] 2) …
```

Fix the build order

---

docs/modules/ROOT/pages/includes/quarkus-mcp-server-stdio.adoc
docs/modules/ROOT/pages/includes/quarkus-mcp-server-stdio_quarkus.mcp.adoc
transports/stdio/deployment/src/main/java/io/quarkiverse/mcp/server/stdio/deployment/McpStdioBuildTimeConfig.java
transports/stdio/deployment/src/main/java/io/quarkiverse/mcp/server/stdio/deployment/StdioMcpServerProcessor.java
transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpMessageHandler.java

Resolves: #155 
The pull request introduces a build time config parameter that controls the initialization of the `mcp-server-stdio` this allows users to have more control over when the server is started.
For my use case, this works like a charm.

feat: Allow mcp-server-stdio to be explicilty started.

---

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java
transports/sse/deployment/src/main/java/io/quarkiverse/mcp/server/sse/deployment/devui/SseMcpDevUIProcessor.java

This is due to an upcoming change in Execution Model Validation [1] where we need the `JsonRPCProvidersBuildItem` produced always, not only in dev mode. JSON RPC providers can use execution model affecting annotations, so we need to know about them, otherwise a non-dev build would fail with an incorrect validation error.
[1] https://github.com/quarkusio/quarkus/pull/46965

Dev UI: always produce JsonRPCProvidersBuildItem

---

cli-adapter/deployment/pom.xml
cli-adapter/deployment/src/main/java/io/quarkiverse/mcp/server/cli/adapter/deployment/CommandUtil.java
cli-adapter/deployment/src/main/java/io/quarkiverse/mcp/server/cli/adapter/deployment/DotNames.java
cli-adapter/deployment/src/main/java/io/quarkiverse/mcp/server/cli/adapter/deployment/McpServerCliAdapterProcessor.java
cli-adapter/deployment/src/test/java/io/quarkiverse/mcp/server/cli/adapter/deployment/CommandUtilTest.java
cli-adapter/integration-tests/pom.xml
cli-adapter/integration-tests/src/main/java/io/quarkiverse/mcp/server/cli/adapter/it/CodeService.java
cli-adapter/integration-tests/src/main/java/io/quarkiverse/mcp/server/cli/adapter/it/CodeServiceCommand.java
cli-adapter/integration-tests/src/test/java/io/quarkiverse/mcp/server/cli/adapter/it/ServerFeaturesIT.java
cli-adapter/pom.xml
cli-adapter/runtime/pom.xml
cli-adapter/runtime/src/main/java/io/quarkiverse/mcp/server/cli/adapter/runtime/AbstractMcpCommand.java
cli-adapter/runtime/src/main/java/io/quarkiverse/mcp/server/cli/adapter/runtime/McpAdapter.java
cli-adapter/runtime/src/main/resources/META-INF/quarkus-extension.yaml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/cli-adapter.adoc
pom.xml
transports/stdio/deployment/src/main/java/io/quarkiverse/mcp/server/stdio/deployment/McpStdioExplicitInitializationBuildItem.java
transports/stdio/deployment/src/main/java/io/quarkiverse/mcp/server/stdio/deployment/StdioMcpServerProcessor.java

Introduce mcp server cli adapter

---

cli-adapter/deployment/src/main/java/io/quarkiverse/mcp/server/cli/adapter/deployment/CommandUtil.java
cli-adapter/deployment/src/main/java/io/quarkiverse/mcp/server/cli/adapter/deployment/McpServerCliAdapterProcessor.java
cli-adapter/deployment/src/test/java/io/quarkiverse/mcp/server/cli/adapter/deployment/CommandUtilTest.java

Resolves: #197
The pull request uses the fully qualified class name for each command adapted to a tool. To avoid having really long names, it eliminates the maximum common package prefix.

fix naming conflict for commands with same class name

---

samples/secure-mcp-sse-server/pom.xml
samples/secure-mcp-sse-server/src/main/resources/application.properties

@mkouba Hi Martin, please update the `main` tomorrow with this update.
FYI, the Keycloak devservice related updated is needed until this project picks up one of the latest Quarkus releases

Set MCP SSE dependency to 1.1.1 in the secure-mcp-sse-server demo

---

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/validation/WrongAnnotationUsageTest.java

- i.e. when a feature annotations is declared on a static method, or a method declared on an interface

core: fail the build if a feature annotation is used incorrectly

---

docs/modules/ROOT/pages/includes/quarkus-mcp-server-sse.adoc
docs/modules/ROOT/pages/includes/quarkus-mcp-server-sse_quarkus.mcp.adoc
transports/sse/deployment/src/main/java/io/quarkiverse/mcp/server/sse/deployment/SseMcpServerProcessor.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/McpServerTest.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/messageendpoint/IncludeQueryParamsTest.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/messageendpoint/QueryParamsNotIncludedByDefaultTest.java
transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpServerRecorder.java
transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/StreamableHttpMcpMessageHandler.java
transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/config/McpSseServerBuildTimeConfig.java
transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/devui/SseMcpJsonRPCService.java

- with `quarkus.mcp.server.sse.message-endpoint.include-query-params=true`
- resolves #287

sse: make it possible to include query params in the message endpoint

---

core/deployment/pom.xml
core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/JsonSchemaGeneratorProcessor.java
core/runtime/pom.xml
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/SchemaGeneratorConfigCustomizer.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/SchemaGeneratorConfigCustomizerJackson.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/SchemaGeneratorConfigCustomizerJakartaValidation.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/SchemaGeneratorConfigCustomizerSwagger2.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolManagerImpl.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/config/McpServerSchemaGeneratorJacksonRuntimeConfig.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/config/McpServerSchemaGeneratorJakartaValidationRuntimeConfig.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/config/McpServerSchemaGeneratorSwagger2RuntimeConfig.java
core/runtime/src/test/java/io/quarkiverse/mcp/server/runtime/SchemaGeneratorConfigCustomizerJacksonTest.java
core/runtime/src/test/java/io/quarkiverse/mcp/server/runtime/SchemaGeneratorConfigCustomizerJakartaValidationTest.java
core/runtime/src/test/java/io/quarkiverse/mcp/server/runtime/SchemaGeneratorConfigCustomizerSwagger2Test.java
docs/modules/ROOT/pages/includes/quarkus-mcp-server-core.adoc
docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.mcp.adoc
docs/modules/ROOT/pages/index.adoc
pom.xml
transports/sse/deployment/pom.xml
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/McpServerTest.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/schemageneration/ToolsSchemaCustomizerCustomTest.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/schemageneration/ToolsSchemaCustomizerJacksonTest.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/schemageneration/ToolsSchemaCustomizerJakartaValidationTest.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/schemageneration/ToolsSchemaCustomizerSwagger2Test.java

Issue https://github.com/quarkiverse/quarkus-mcp-server/issues/289
This PR adds support to customize the Victools SchemaGenerator used by the MCP Server extension.
For the modules `com.github.victools:jsonschema-module-jackson`, `com.github.victools:jsonschema-module-jakarta-validation` and `com.github.victools:jsonschema-module-swagger-2`, automatic detection of these modules is added and customizers are added to configure these modules on the SchemaGenerator.

Issue 289 - Add support for annotation-based schema generation for nested tool argument classes

---

core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureManagerBase.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpLogImpl.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/logging/LoggingStreamableTest.java

- do not cache McpLog but merely the Logger instances
- fixes #308

core: fix McpLog for stremable transport

---

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java
transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/annotations/ToolAnnotationsTest.java

When creating a tool like shown below: 
```java
@Tool(annotations = @Annotations(readOnlyHint = true, destructiveHint = false))
String withoutTitle() {
return "ok";
}
```
it results in an NPE: 
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[error]: Build step io.quarkiverse.mcp.server.deployment.McpServerProcessor#generateMetadata threw an exception: java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:233)
at io.quarkus.gizmo.BytecodeCreatorImpl.load(BytecodeCreatorImpl.java:319)
at io.quarkiverse.mcp.server.deployment.McpServerProcessor.processFeatureMethod(McpServerProcessor.java:974)
at io.quarkiverse.mcp.server.deployment.McpServerProcessor.generateMetadata(McpServerProcessor.java:524) …
```

NPE when annotating with Tool @Annotations without title. 

---

core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceManager.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessageHandler.java
test/src/main/java/io/quarkiverse/mcp/server/test/McpStreamableTestClientImpl.java

- also update supported MCP versions

core: remove deprecated ResourceInfo#sendUpdate()

---

transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpServerRecorder.java
transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpServerRecorder.java

With https://github.com/quarkusio/quarkus/pull/48500, we will disallow the injection of Runtime configuration objects during deployment. The recommended way is to inject it directly into the Recorder, wrapped in a `RuntimeValue`.

Do not use Runtime configuration during deployment

---

core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpObjectMapperCustomizer.java

- there is no reason to keep it in the singleton context

Change the scope of McpObjectMapperCustomizer to dependent

---

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/DefaultSchemaGenerator.java
core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpObjectMapperCustomizer.java

- because ObjectMapper is initialized during STATIC_INIT which may cause troubles when a SchemaGeneratorConfigCustomizer depends on runtime configuration mapping
This was fixed within https://github.com/quarkiverse/quarkus-mcp-server/pull/438 for the main branch.

Extract the ObjectMapperCustomizer logic from DefaultSchemaGenerator
