quarkiverse/quarkus-mcp-server

README.md, deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java, deployment/src/test/java/io/quarkiverse/mcp/server/test/prompts/InvalidPromptNameTest.java, deployment/src/test/java/io/quarkiverse/mcp/server/test/prompts/MissingPromptArgumentTest.java, deployment/src/test/java/io/quarkiverse/mcp/server/test/prompts/PromptInternalErrorTest.java, deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/InvalidResourceUriTest.java, deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/ResourceInternalErrorTest.java, deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/InvalidToolNameTest.java, deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/MissingToolArgumentTest.java, deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/ToolInternalErrorTest.java, docs/modules/ROOT/pages/includes/quarkus-mcp-server.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server_quarkus.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server_quarkus.mcp.adoc, docs/modules/ROOT/pages/index.adoc, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ArgumentProviders.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureManager.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/JsonRPC.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpException.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessagesHandler.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/Messages.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptManager.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptMessageHandler.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceManager.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceMessageHandler.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolManager.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolMessageHandler.java, runtime/src/main/java/io/quarkiverse/mcp/server/runtime/config/McpRuntimeConfig.java
=> Implement error handling

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/Tool.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ToolResponse.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResultMappers.java, docs/modules/ROOT/pages/index.adoc, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/MyTools.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/ToolsTest.java
=> Tools: annotated method may return String, Uni<String>, List<String>

samples/weather/README.md
- **add weather sample server**
- **document the jbang option**
=> better readme for sample

core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptCompletionMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceTemplateMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolMessageHandler.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpServerRecorder.java
=> Use DEBUG log level at runtime

core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolMessageHandler.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/MyTools.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/ToolsTest.java
- skip special method parameters (connection, log, etc.)
=> tools: fix input schema generation

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/DotNames.java, core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/FeatureMethodBuildItem.java, core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/CompleteResourceTemplate.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/CompletionMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureMetadata.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMetadata.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptCompleteMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceTemplateCompleteManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceTemplateCompleteMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResultMappers.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolMessageHandler.java, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.adoc, docs/modules/ROOT/pages/index.adoc, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/complete/InvalidResourceTemplateCompleteTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/complete/MyResourceTemplates.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/complete/ResourceTemplateCompleteTest.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpMessageHandler.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpServerRecorder.java, transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpMessageHandler.java, transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpServerRecorder.java
=> Implement completion for resource templates

core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ConnectionManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/JsonRPC.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpConnectionBase.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/Messages.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/config/McpRuntimeConfig.java, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.mcp.adoc, test-utils/src/main/java/io/quarkiverse/mcp/server/test/McpSseClient.java, transports/sse/deployment/src/main/java/io/quarkiverse/mcp/server/sse/deployment/SseMcpServerProcessor.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/ping/AutoPingIntervalTest.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpConnection.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpMessageHandler.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpServerRecorder.java, transports/stdio/deployment/src/main/java/io/quarkiverse/mcp/server/stdio/deployment/StdioMcpServerProcessor.java, transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpConnection.java, transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpMessageHandler.java, transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpServerRecorder.java
- enabled with quarkus.mcp.server.auto-ping-interval config property
- resolves #74
=> core: introduce auto ping feature

docs/modules/ROOT/pages/index.adoc, transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioConfigBuilderCustomizer.java
=> stdio: redirect console logging to stderr

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/DotNames.java, core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/RequestUri.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ArgumentProviders.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/CompletionMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureArgument.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceTemplateManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolMessageHandler.java, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.adoc, docs/modules/ROOT/pages/index.adoc, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/complete/MyResourceTemplates.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/MyResources.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/ResourceInternalErrorTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/templates/MyTemplates.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/validation/ResourceTemplateInvalidParamTest.java, transports/sse/integration-tests/src/main/java/io/quarkiverse/mcp/server/sse/it/ServerFeatures.java, transports/stdio/integration-tests/src/main/java/io/quarkiverse/mcp/server/stdio/it/ServerFeatures.java
=> core: improve feature methods params validation

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/DotNames.java, core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/FeatureMethodBuildItem.java, core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java, docs/modules/ROOT/pages/index.adoc, transports/sse/deployment/pom.xml, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/MyTools.java
=> Support Tool/P annotations from Lanchain4j

docs/modules/ROOT/pages/includes/quarkus-mcp-server-sse.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server-sse_quarkus.mcp.adoc, transports/sse/deployment/src/main/java/io/quarkiverse/mcp/server/sse/deployment/SseMcpServerProcessor.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/McpServerTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/rootpath/CustomRootPathSlashTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/rootpath/CustomRootPathTest.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpServerRecorder.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/config/McpSseBuildTimeConfig.java
- for example quarkus.mcp.server.sse.root-path=/
=> sse: fix custom root path

core/runtime/src/main/java/io/quarkiverse/mcp/server/FeatureManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/CompletionManagerBase.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/Cursor.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureManagerBase.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/Messages.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/Page.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceTemplateManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceTemplateMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/config/McpRuntimeConfig.java, core/runtime/src/test/java/io/quarkiverse/mcp/server/runtime/CursorTest.java, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.mcp.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server-sse_quarkus.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server-stdio_quarkus.adoc, docs/modules/ROOT/pages/index.adoc, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/prompts/PromptsPaginationTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/ResourcesPaginationTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/templates/ResourceTemplatesPaginationTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/ToolsPaginationTest.java
- see also https://spec.modelcontextprotocol.io/specification/2024-11-05/server/utilities/pagination/
=> Add pagination support

core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ListEncoderResultMapper.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolEncoderResultMapper.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/ToolCustomResponseEncoderTest.java
- previously it was not used for List<E> and Uni<List<E> at all
=> tools: ToolResponseEncoder should always take precedence

core/runtime/pom.xml, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceTemplateManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolManagerImpl.java, devtools/stdio-sse-proxy/pom.xml, devtools/stdio-sse-proxy/src/main/java/io/quarkiverse/mcp/server/proxy/StdioSseProxy.java, pom.xml, samples/weather/pom.xml, samples/weather/src/main/resources/application.properties, sse-client/pom.xml, sse-client/src/main/java/io/quarkiverse/mcp/server/sse/client/SseClient.java, test-utils/src/main/java/io/quarkiverse/mcp/server/test/McpSseClient.java, transports/sse/deployment/src/main/java/io/quarkiverse/mcp/server/sse/deployment/devui/SseMcpDevUIProcessor.java, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-prompts.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-resource-templates.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-resources.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-tools.js, transports/sse/runtime/pom.xml, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/devui/SseMcpJsonRPCService.java, transports/sse/runtime/src/main/resources/META-INF/quarkus-extension.yaml
=> Initial Dev UI support

transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-prompts.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-resource-templates.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-resources.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-tools.js, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/devui/SseMcpJsonRPCService.java
- remove test messages from the map
- minor UI tweaks
=> sse: dev ui updates

sse-client/src/main/java/io/quarkiverse/mcp/server/sse/client/SseClient.java
=> sse client: fix the problem with superfluous new lines (again)

core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolManagerImpl.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/McpServerTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/OptionalListStringInputSchemaTest.java
=> core: fix tools input schema generation for Optional<List<String>>

core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureManagerBase.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/Types.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/NumberArgumentTest.java
=> core: fix tools number argument coercion

docs/modules/ROOT/pages/cli-adapter.adoc, docs/modules/ROOT/pages/index.adoc
Here are a few minor improvements to the doc (I wanted to know more about what we were doing thus why I read the doc).
Unfortunately VScode went a bit berserk as for end of line spaces. I recommend to disable whitespace change to review this.
Feel free to push back on any change, I'll adjust accordingly.
=> Some micro improvements to the doc

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/PromptMessage.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/Role.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/complete/MyPrompts.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/complete/PromptProgrammaticCompleteTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/prompts/MyPrompts.java
=> PromptMessage#role() should be an enum

docs/antora.yml
It is displayed in the nav here:
https://docs.quarkiverse.io/quarkus-mcp-server/dev/index.html
Again no rocket science but I noticed it while reading the doc.
=> Fix case in antora.yml

core/runtime/src/main/java/io/quarkiverse/mcp/server/CompletionManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/CompletionManagerBase.java, transports/sse/deployment/src/main/java/io/quarkiverse/mcp/server/sse/deployment/devui/SseMcpDevUIProcessor.java, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-prompt-completions.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-resource-template-completions.js, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/devui/SseMcpJsonRPCService.java, transports/sse/runtime/src/main/resources/META-INF/quarkus-extension.yaml, transports/stdio/runtime/src/main/resources/META-INF/quarkus-extension.yaml
=> Dev UI - implement views for completion APIs

sse-client/src/main/java/io/quarkiverse/mcp/server/sse/client/SseClient.java, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-prompt-completions.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-prompts.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-resource-template-completions.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-resource-templates.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-resources.js, transports/sse/deployment/src/main/resources/dev-ui/qwc-mcp-tools.js, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/devui/SseMcpJsonRPCService.java
- also make it possible to force a new MCP session
=> devui: add input field for bearerToken header

.github/workflows/build.yml, samples/secure-mcp-sse-server/pom.xml, samples/weather/pom.xml, samples/weather/src/main/resources/application.properties, update-samples.sh
This PR supersedes https://github.com/quarkiverse/quarkus-mcp-server/pull/231.
I don't think we need parallelization or some advanced automation at this stage.
@kpavlov WDYT?
=> samples: update MCP server version, add CI build

transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/devmode/MyTools.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/devmode/ToolChangeTest.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/devui/SseMcpJsonRPCService.java
- instead of VertxHttpConfig and VertxHttpBuildTimeConfig config mappings
=> devmode: use config properties in SseMcpJsonRPCService

core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureManagerBase.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpRequest.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpRequestImpl.java, docs/modules/ROOT/pages/index.adoc, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/batch/ToolBatchTest.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpMessageHandler.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/StreamableHttpMcpMessageHandler.java, transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpMessageHandler.java
=> Fix CDI request context activation for batch processing

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/FeatureMethodBuildItem.java, core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/Tool.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ToolManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureMethodInfo.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolManagerImpl.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/McpServerTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/annotations/ToolAnnotationsTest.java
- add declarative and programmatic API to specify tool annotations
- resolves #280
=> core: support tool annotations

core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpLogImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/Messages.java, sse-client/src/main/java/io/quarkiverse/mcp/server/sse/client/SseClient.java, test/src/main/java/io/quarkiverse/mcp/server/test/McpAssured.java, test/src/main/java/io/quarkiverse/mcp/server/test/McpStreamableClient.java, test/src/main/java/io/quarkiverse/mcp/server/test/McpStreamableTestClientImpl.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/close/CloseTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/connectionidletimeout/ConnectionIdleTimeoutTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/streamablehttp/SubsidiarySseTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/streamablehttp/TerminateSessionTest.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpMessageHandler.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpServerRecorder.java, transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/StreamableHttpMcpConnection.java
=> streamable: support "subsidiary" SSE streams

docs/modules/ROOT/pages/index.adoc, test/pom.xml, test/src/main/java/io/quarkiverse/mcp/server/test/McpQuarkusTestBeforeEachCallback.java, test/src/main/resources/META-INF/services/io.quarkus.test.junit.callback.QuarkusTestBeforeEachCallback, transports/sse/integration-tests/src/main/resources/application.properties, transports/sse/integration-tests/src/test/java/io/quarkiverse/mcp/server/sse/it/ServerFeaturesTest.java
=> McpAssured: set the baseUri automatically in a Quarkus test

core/runtime/src/main/java/io/quarkiverse/mcp/server/CompletionManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/PromptManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceTemplateManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ToolManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/CompletionManagerBase.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureManagerBase.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpConnectionBase.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/PromptManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceTemplateManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolManagerImpl.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/cancel/CancellationTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/prompts/ProgrammaticPromptTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/ProgrammaticResourceTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/ProgrammaticToolTest.java
=> cancellations: add support to programmatic API

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/FeatureMethodBuildItem.java, core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/OutputSchemaGenerator.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/Tool.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ToolManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ToolResponse.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/DefaultSchemaGenerator.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/EncoderMapper.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/EncoderResultMapper.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureManagerBase.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureMetadata.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureMethodInfo.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ListEncoderResultMapper.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResultMappers.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolEncoderResultMapper.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ToolStructuredContentResultMapper.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/config/McpServerRuntimeConfig.java, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.mcp.adoc, docs/modules/ROOT/pages/index.adoc, test/src/main/java/io/quarkiverse/mcp/server/test/McpAssured.java, test/src/main/java/io/quarkiverse/mcp/server/test/McpTestClientBase.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/structcontent/ToolStructuredContentCompatibilityModeTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/structcontent/ToolStructuredContentTest.java
=>  core: support for structured tool output

core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/FeatureMethodBuildItem.java, core/deployment/src/main/java/io/quarkiverse/mcp/server/deployment/McpServerProcessor.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/AudioContent.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/BlobResourceContents.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/Content.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/EmbeddedResource.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ImageContent.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/Resource.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceContents.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceLink.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceTemplate.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/ResourceTemplateManager.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/TextContent.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/TextResourceContents.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/Contents.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureMetadata.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/FeatureMethodInfo.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceManagerImpl.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/ResourceTemplateManagerImpl.java, test/src/main/java/io/quarkiverse/mcp/server/test/McpAssured.java, test/src/main/java/io/quarkiverse/mcp/server/test/McpTestClientBase.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/MyResources.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/ProgrammaticResourceTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/ResourcesTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/templates/MyTemplates.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/templates/ProgrammaticResourceTemplateTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/resources/templates/ResourceTemplatesTest.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/MyTools.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/tools/ToolsTest.java
=> core: support annotations for resources/templates and contents

pom.xml
Also cleanup pom.xml from values already defined in quarkiverse-parent
=> Introduce quarkus-mcp-server-bom

transports/sse/runtime/src/main/java/io/quarkiverse/mcp/server/sse/runtime/SseMcpServerRecorder.java, transports/stdio/runtime/src/main/java/io/quarkiverse/mcp/server/stdio/runtime/StdioMcpServerRecorder.java
=> Do not use Runtime configuration during deployment

core/runtime/src/main/java/io/quarkiverse/mcp/server/InitialRequest.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessageHandler.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/config/McpServerRuntimeConfig.java, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core.adoc, docs/modules/ROOT/pages/includes/quarkus-mcp-server-core_quarkus.mcp.adoc, test/src/main/java/io/quarkiverse/mcp/server/test/McpAssured.java, test/src/main/java/io/quarkiverse/mcp/server/test/McpSseTestClientImpl.java, test/src/main/java/io/quarkiverse/mcp/server/test/McpStreamableTestClientImpl.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/serverinfo/CustomServerInfoTest.java
See https://modelcontextprotocol.io/specification/2025-06-18/schema#initializeresult-instructions
=> fixes #407: Add instructions support in the InitialRequest

cli-adapter/integration-tests/src/test/java/io/quarkiverse/mcp/server/cli/adapter/it/ServerFeaturesIT.java, core/runtime/src/main/java/io/quarkiverse/mcp/server/runtime/McpMessageHandler.java, transports/sse/deployment/src/test/java/io/quarkiverse/mcp/server/test/init/InitTest.java
=> Activate request context during Notification.Type.INITIALIZED

docs/modules/ROOT/pages/index.adoc
Ref issue https://github.com/quarkiverse/quarkus-mcp-server/issues/426
=> docs: add warning about compatibility mode on Tools response's structured content
